### ISSUE TITLE
Unable to import module numerous

### ISSUE THREAD

**Issue by spuder** [outofmbufs/Nappy#1]
I"m unable to get this module to work.

According to the instructions it should be as easy as

    pip install numerous

Then a script like:

```python
import sys
import os
from numerous import Numerous

n_key = os.environ["NUMEROUS_KEY"]
n_humidity1 = os.environ["NUMEROUS_HUMIDITY1"]

foo = Numerous(apiKey=n_key)
h1 = foo.metric(n_humidity1)

h1.write(42)
```

However that throws this error. 

```
root@raspberrypi:~# python /home/pi/temperature/sandbox/numerous.py
Traceback (most recent call last):
  File "/home/pi/temperature/sandbox/numerous.py", line 3, in <module>
    from numerous import Numerous
  File "/home/pi/temperature/sandbox/numerous.py", line 3, in <module>
    from numerous import Numerous
ImportError: cannot import name Numerous
```

I've tried installing the python library from pip as both myself and as root with the same results. 

Is there a secret to getting this working? Looks awesome, but my lack of python skills is preventing me from using it.

**Comment by outofmbufs** [comment]
Ah - this is an obscure problem! ... your file is named "numerous.py" so "from numerous import Numerous" is trying to find "Numerous" (recursively) inside your own file!

Rename your script to somethingelse.py and see if that fixes it.

**Comment by outofmbufs** [comment]
See response on github - let me know if this does/doesn't fix it.

        - neil

P.S. This one puzzled me for a bit so don't feel bad! I believe this
behavior of being able to "import from yourself" is related to the idea of
using a module itself as a shell-level command (which I don't use but
probably should have - it's a cleaner way to implement things like the
shell-cmd stuff). Anyhow, rename your test file and see if it works.

**Comment by spuder** [comment]
Thank you so much. That did it. I had to revert from calling the object `numerous.Numerous` back to just `numerous` and it looks like it works. 

```python
import sys
import os
from numerous import Numerous
#import numerous

n_key = os.environ["NUMEROUS_KEY"]
n_humidity1 = os.environ["NUMEROUS_HUMIDITY1"]
n_temp_f1 = os.environ["NUMEROUS_TEMP_F1"]

#foo = numerous.Numerous(apiKey=n_key)
foo = Numerous(apiKey=n_key)
h1 = foo.metric(n_humidity1)
tf1 = foo.metric(n_temp_f1)

h1.write(44)
```


I still get a warning, but I'm not too worried about it. 

```bash
python num-test.py
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by outofmbufs** [comment]
Yeah, that warning is annoying; I've seen it. It's related to the age of the python in that raspberry pi distribution. If you do follow the given URL in the warning it tells you how you can silence it if you really care. 

The warning is not specific to Numerous; it's one of the other layers telling you that the SSL implementation is "inadequate" (except it's not an issue for talking to numerous and so you can just ignore it).

Glad you've got it working!
