### ISSUE TITLE
Support keyring for passwords.

### ISSUE THREAD

**Issue by hardkrash** [outofmbufs/Nappy#2]
There is a great password keyring interface that supports Linux, OS X, and Windows password vaults.

https://pypi.python.org/pypi/keyring

Please consider adding keyring for getting passwords securely.

**Comment by outofmbufs** [comment]
This one I don't "get" just yet - something more than along these lines which you can already do:

    nr = numerous.Numerous(apiKey=keyring.get_password(blah))

?

**Comment by hardkrash** [comment]
Nope, i just didn't see that tree in the forest.

I saw all of the other password entry options and didn't think about ```apiKey=keyring.get_password(blah)```

I would suggest that the docs promote keyring as an option.

**Comment by outofmbufs** [comment]
FYI reworked https://github.com/outofmbufs/Nappy/wiki/APIKey-Management accordingly.

**Comment by hardkrash** [comment]
That's great!
